### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [inagakiyuya/stressdiary#5]
ご提出ありがとうございます。
以下の観点からレビューを行います。

```
1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

---

### １について
・日記・ストレス・幸せ度の投稿ができるのを確認しました。
・投稿されたものがグラフに反映されるのを確認しました。

=> 1日に複数回投稿すると、100点を超える結果がグラフ上に表示されてしまいますが、この挙動はサービス上問題ないでしょうか？比較という点では1日に3回投稿したグラフと1回投稿したグラフが混在してしまうのは、比較できていないという気がするのですが確認をお願いします。

<br />

### ２について
Pull requestsの方に、本サービスのコードが全て記載されている感じかと思いますが、これはベースブランチにマージしていないということは破棄する可能性があるということでしょうか？ベースブランチのコードを元にレビューしますのでご確認をお願いします。

またプルリクエストの方に余計なファイルが含まれていたり、使っていないファイルもgitに含まれているようですので、適切な対応（余計なファイルはアップしない＆使っていないファイルは削除するetc）をお願いいたします。

<br />

### ３について
・結論から申し上げると現状厳しいかと思われます。グラフ部分やストレス・幸福度入力部分、検索等も触れましたが、就活に足りうる技術力をアピールできる点は乏しいように感じました。以下の機能の実装も行いましょう。

```
【マルチ検索・オートコンプリート】（日記・ストレス解消法に関しての検索部分）
概要：食べログの検索フォームのような、様々なカラムから検索可能な検索フォームです。1文字入力するたびに、候補が表示されるため、ユーザーの入力手間を減らし、入力ミスを減らすことができます。

使用技術・ライブラリ：
- Stimulus Autocomplete（Rails7 ）
  - https://github.com/afcapel/stimulus-autocomplete
- JQuery
  - https://github.com/xpeppers/rails-autocomplete


【レコメンド】（自分に合ったストレス解消法を提示する）
概要：投稿されたまたは事前に用意されたコンテンツと類似したコンテンツを推奨する機能をレコメンドと呼びます。代表的なアルゴリズムとして、協調フィルタリングとコンテンツフィルタリングがあります。協調フィルタリングは、ユーザの行動や嗜好データを元に類似度を算出し、コンテンツベースフィルタリングは、コンテンツの数値化された特徴や評価を元に類似度を算出します。

使用技術・ライブラリ：
- Amazon Personalize
 
 - https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/what-is-personalize.html
  - AWSが提供する機械学習の知識がなくても、個々のユーザー向けにリコメンデーションをリアルタイムで提供できるサービスです。
- GCP Recommendations AI
  - https://cloud.google.com/recommendations?hl=ja
  - Recommendations AIは、Google Cloud Platformが提供するレコメンドエンジンであり、Googleの機械学習アルゴリズムを利用しています。
- アルゴリズム
  - 協調フィルタリングやコンテンツベースフィルタリングは、一般的にアルゴリズムが公開されているので、RubyやPythonで独自に実装することも可能です。

【LINE通知】（毎日の投稿を忘れないように。本リリースまでに）
概要：Webプッシュはまだ普及しておらず、アプリのプッシュ通知を利用したい方には、LINEプッシュ通知がおすすめです。簡単な連携で、自分の好きなタイミングにLINEを通じてプッシュ通知を行うことができます。

使用技術・ライブラリ：
- LINE Messaging API
  - LINE Messaging API SDK for Ruby
  - https://github.com/line/line-bot-sdk-ruby
```

・レコードの取得に関してはscopeを使ったり、クラスメソッドを定義＆使用して呼び出すようにしましょう。

・以下のルーティング部分もresourceベースのルーティングを組みましょう。また以下に関して言うと、profileからネストさせていますが、profileからネストさせる必要があるか考えてみましょう。
```ruby
member do
  get :mymean
  get :bookmarks
  get :mydiary
  get :favorites
  get :stress_chart
  get :happy_chart
  get :like_ranking
  get :like_ranking_in_past_month
  get :like_ranking_in_past_week
  get :sympathy_ranking
  get :sympathy_ranking_in_past_month
  get :sympathy_ranking_in_past_week
end
```

<br />

### ４について
・基礎編のRailsとほぼ同じ見た目の印象だったので、改修した方がよいかと思いました。
・使い方に関して説明が必要かと思います。現状だと何ができるアプリ・どう使えばよいかが分からない状態かと思います。
・日記の記入内容を3行に制限とありましたが、３行以上記入できたのでご確認をお願いします。
・ストレス＆幸福度チェックも縦に長くあって入力がやや面倒に感じました。入力の簡略化という点では見せ方・チェックに入れる＆外しやすさを考慮したほうが良いと思いました。

<br />

### その他
・上記修正＆追加機能が完了する目処を教えてください。
・上記修正＆追加機能の後に追加実装する機能と実装までに必要な日数を教えてください。
・追加実装まで含めた上記が完了する目処（本リリース）、日数を教えてください。

**Comment by inagakiyuya** [comment]
お疲れ様です。MVPリリースのレビューありがとうございます。
### **1について**
・複数回日記を投稿するとグラフがおかしくなる点については見落としていたので、改善したいと思います。
### **2について**
・私の理解不足で申し訳ないのですが、なぜ、mainブランチにコードが存在せず、developブランチにコードが存在するのかという認識で宜しいでしょうか？
=>上記の認識で回答をすると、後ほど、mergeをします。ご指摘ありがとうございます。
・余計なファイルは削除するか、githubから取り消すようにします。
### **3について**
・レコードの取得の件ですが、どこの部分のことなのかが分からないので、返信をお願いします。
・機能不足の件ですが、紹介された機能の実装をするようにします。
・ネストの件なのですが、もう一度、考えてみます。
### **4について**
・見た目に関しては、カリキュラムを参考にデザインを考えたので、もう少しオリジナリティ溢れるデザインにしていけたらいいかなと思います。
・使い方に関しては、Read Meを編集して伝わりやすいようにするか、アプリ内にintroductionの画面を挿入することで、ユーザーに利用方法が伝わりやすいようにします。
・診断テストのチェックボックスに関しては、デザインをもう少し改良しようと思います。
・3行以上日記が記入できてしまう部分に関しては、修正します。
### **その他**
・上記修正&追加機能が完了する目処
実装したことが無い機能なので何とも言えないですが
理想は2週間以内に完了させたいです。
・上記修正&追加機能が完了してから追加実装する機能と実装までに必要な日数
今現在、特に追加で実装する予定は無いのですが、実装する場合はパスワードリセット機能を実装しようと思います。この機能はカリキュラムで一回取り扱ったので、一日で実装できると思います。
・本リリースの日程
2週間半で本リリースをしたいです。

**Comment by Tsuchiya2** [comment]
回答します。また確認事項もあるので回答をお願いします。

> レコードの取得の件ですが、どこの部分のことなのかが分からないので、返信をお願いします。

以下のようなjoinsメソッドからの部分などがそれに当たりますね。他にも散見されるので確認をお願いします。

```ruby
# app/controllers/mypage/profiles_controller.rb
  def stress_chart
    @diaries = current_user.diaries.includes(:stress_diagnosis)
    @stress_datas = @diaries
                    .joins(:stress_diagnosis)
                    .where('diaries.created_at >= ?', 31.days.ago)
                    .where('stress_diagnoses.stress_count >= ?', 0)
                    .select("date(diaries.created_at) as date, stress_diagnoses.stress_count")
                    .order("date ASC")
                    .group_by { |d| d.date }
                    .map { |date, rows| [date.to_s, rows.sum(&:stress_count)] }
  end
```

<br />

> ・上記修正&追加機能が完了する目処
実装したことが無い機能なので何とも言えないですが
理想は2週間以内に完了させたいです。
・上記修正&追加機能が完了してから追加実装する機能と実装までに必要な日数
今現在、特に追加で実装する予定は無いのですが、実装する場合はパスワードリセット機能を実装しようと思います。この機能はカリキュラムで一回取り扱ったので、一日で実装できると思います。
・本リリースの日程
2週間半で本リリースをしたいです。

上記に関しては紹介した機能候補も含めて2週間半後に本リリースまで行うという認識で良かったでしょうか。

**Comment by inagakiyuya** [comment]
お疲れ様です。
2週間半を目標に、指摘された部分を含めて本リリースを行いたいと思います。
宜しくお願いします。

**Comment by Tsuchiya2** [comment]
返信ありがとうございます。
現状では就活に望むには厳しい状況ですので、コメントした内容の実装＆修正に加えて、ユーザーからのフィードバックを取りにいって、その情報をアプリケーションに反映していきましょう。
